# -*- coding: utf-8 -*-
"""LinearRegressionProject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dQlYdgGxoUhUu0AKUUr01vqAq3m3rp5K
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn import metrics

df = pd.read_csv('Ecommerce Customers.txt')

print(df.head())
print(df.info())
print(df.describe())

X = df[['Avg. Session Length', 'Time on App', 'Time on Website', 'Length of Membership']]
Y = df[['Yearly Amount Spent']]

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state=42)

sns.jointplot(x='Time on Website', y='Yearly Amount Spent', data=df, alpha=0.5)

sns.jointplot(x='Time on App', y='Yearly Amount Spent', data=df, alpha=0.5)

sns.jointplot(x='Time on App', y='Length of Membership', kind='hex', data=df)

sns.pairplot(df)

sns.lmplot(x='Length of Membership', y='Yearly Amount Spent', data=df)

lm = LinearRegression()
lm.fit(X_train,Y_train)

print(lm.coef_)

predictions = lm.predict(X_test)

plt.scatter(Y_test,predictions)
plt.xlabel("Values")
plt.ylabel("Predictions")

print('MAE:',metrics.mean_absolute_error(Y_test,predictions))
print('MSE:',metrics.mean_squared_error(Y_test,predictions))
print('RMSE:',np.sqrt(metrics.mean_squared_error(Y_test,predictions)))